server:
  port: 8082
spring:
  application:
    name: mall-demo
  # Customize Spring Boot Info actuator
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tehran
    username: root
    password: root
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
management: #Enable monitoring of SpringBoot Admin
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}
  application.encoding: '@project.build.sourceEncoding@'
  application.name: ${spring.application.name}
  spring.boot.version: '@spring-boot.version@'

feign:
  okhttp:
    enabled: true
