version: '3'
services:
  mall-admin:
    image: mall/mall-admin:1.0-SNAPSHOT
    container_name: mall-admin
    ports:
      - 8080:8080
    volumes:
      - /mydata/app/mall-admin/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Tehran"'
    external_links:
      - mysql:db #You can use the domain name db to access the mysql service
      - nacos-registry:nacos-registry #Nacos service can be accessed with the domain name nacos-registry
  mall-search:
    image: mall/mall-search:1.0-SNAPSHOT
    container_name: mall-search
    ports:
      - 8081:8081
    volumes:
      - /mydata/app/mall-search/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Tehran"'
    external_links:
      - elasticsearch:es #You can use the domain name es to access the elasticsearch service
      - mysql:db #You can use the domain name db to access the mysql service
      - nacos-registry:nacos-registry #Nacos service can be accessed with the domain name nacos-registry
  mall-portal:
    image: mall/mall-portal:1.0-SNAPSHOT
    container_name: mall-portal
    ports:
      - 8085:8085
    volumes:
      - /mydata/app/mall-portal/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Tehran"'
    external_links:
      - redis:redis #You can use the domain name redis to access the redis service
      - mongo:mongo #You can use the mongo domain name to access the mongo service
      - mysql:db #You can use the domain name db to access the mysql service
      - rabbitmq:rabbit #The rabbitmq service can be accessed with the domain name rabbit
      - nacos-registry:nacos-registry #Nacos service can be accessed with the domain name nacos-registry
  mall-auth:
    image: mall/mall-auth:1.0-SNAPSHOT
    container_name: mall-auth
    ports:
      - 8401:8401
    volumes:
      - /mydata/app/mall-auth/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Tehran"'
    external_links:
      - nacos-registry:nacos-registry #Nacos service can be accessed with the domain name nacos-registry
  mall-gateway:
    image: mall/mall-gateway:1.0-SNAPSHOT
    container_name: mall-gateway
    ports:
      - 8201:8201
    volumes:
      - /mydata/app/mall-gateway/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Tehran"'
    external_links:
      - redis:redis #You can use the domain name redis to access the redis service
      - nacos-registry:nacos-registry #Nacos service can be accessed with the domain name nacos-registry
  mall-monitor:
    image: mall/mall-monitor:1.0-SNAPSHOT
    container_name: mall-monitor
    ports:
      - 8101:8101
    volumes:
      - /mydata/app/mall-monitor/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Tehran"'
    external_links:
      - nacos-registry:nacos-registry #Nacos service can be accessed with the domain name nacos-registry