version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #Set the root account password
    ports:
      - 3306:3306
    volumes:
      - /mydata/mysql/data/db:/var/lib/mysql #Data file mounting
      - /mydata/mysql/data/conf:/etc/mysql/conf.d #Configuration file mounting
      - /mydata/mysql/log:/var/log/mysql #Log file mount
  redis:
    image: redis:5
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - /mydata/redis/data:/data #Data file mounting
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.10
    container_name: nginx
    volumes:
      - /mydata/nginx/nginx.conf:/etc/nginx/nginx.conf #Configuration file mounting
      - /mydata/nginx/html:/usr/share/nginx/html #Static resource root directory mount
      - /mydata/nginx/log:/var/log/nginx #Log file mount
    ports:
      - 80:80
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    volumes:
      - /mydata/rabbitmq/data:/var/lib/rabbitmq #Data file mounting
      - /mydata/rabbitmq/log:/var/log/rabbitmq #Log file mount
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    user: root
    environment:
      - "cluster.name=elasticsearch" #Set the cluster name to elasticsearch
      - "discovery.type=single-node" #Start in single node mode
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #Set the use of jvm memory size
    volumes:
      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #Plug-in file mounting
      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data #Data file mounting
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:7.8.0
    container_name: logstash
    environment:
      - TZ=Asia/Tehran
    volumes:
      - /mydata/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #Mount the configuration file of logstash
    depends_on:
      - elasticsearch #Kibana starts after elasticsearch starts
    links:
      - elasticsearch:es #You can use the domain name es to access the elasticsearch service
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:7.8.0
    container_name: kibana
    links:
      - elasticsearch:es #You can use the domain name es to access the elasticsearch service
    depends_on:
      - elasticsearch #Kibana starts after elasticsearch starts
    environment:
      - "elasticsearch.hosts=http://es:9200" #Set the address to access elasticsearch
    ports:
      - 5601:5601
  mongo:
    image: mongo:4.2.5
    container_name: mongo
    volumes:
      - /mydata/mongo/db:/data/db #Data file mounting
    ports:
      - 27017:27017
  consul:
    image: consul:latest
    container_name: consul
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    volumes:
      - /mydata/consul/data:/consul/data
    ports:
      - 8500:8500
      - 8600:8600/udp
  minio:
    image: minio/minio
    container_name: minio
    command: server /data gateway s3
    environment:
      - "MINIO_ACCESS_KEY=mallminio"
      - "MINIO_SECRET_KEY=mallminio"
    volumes:
      - /mydata/minio/data:/data
    ports:
      - 9090:9000