spring:
  application:
    name: mall-auth
server:
  port: 8401
# Customize Spring Boot Info actuator
info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}
  application.encoding: @project.build.sourceEncoding@
  application.name: ${spring.application.name}
  spring.boot.version: @spring-boot.version@
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000 #Service request connection timeout time (ms)
  ReadTimeout: 3000 #Service request processing timeout time (ms)
