server:
  port: 8080
spring:
  application:
    name: mall-admin
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tehran
    username: root
    password: root
    druid:
      initial-size: 5 #Initial connection pool size
      min-idle: 10 #Minimum number of idle connections
      max-active: 20 #Maximum number of connections
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #Exclude these file type request data
      stat-view-servlet: #Login user name and password to access the monitoring webpage
        login-username: druid
        login-password: druid
  redis:
    host: localhost # Redis server address
    database: 0 # Redis database index (default is 0)
    port: 6379 # Redis server connection port
    password:  # Redis server connection password (empty by default)
    timeout: 3000ms # Connection timeout (ms)
  rabbitmq: #rabbitmq related configuration
    host: localhost
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      enabled: true #Open file upload
      max-file-size: 10MB #Limit file upload size to 10 M
# Customize Spring Boot Info actuator
info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}
  application.encoding: '@project.build.sourceEncoding@'
  application.name: ${spring.application.name}
  spring.boot.version: '@spring-boot.version@'
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management: #Open SpringBoot Admin monitoring
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
redis:
  database: mall
  key:
    admin: 'ums:admin'
  expire:
    common: 86400 # 24 hours
aws:
  s3:
    endpoint: localhost:9000 # Access domain name of oss external service
    accessKeyId: ${ACCESS_KEY} # User ID used in access authentication
    accessKeySecret: ${SECRET_KEY} # The key used by the user to encrypt the signature string and s3 to verify the signature string
    bucketName: mall-s3 # s3 storage space
    region: us-east-1
    policy:
      expire: 300 # Signature validity period(S)
    maxSize: 10 # Upload file size(M)
    callback: http://39.98.190.128:8080/aws/s3/callback # Callback address after successful file upload
    dir:
      prefix: mall/images/ # Upload folder path prefix
minio:
  endpoint: localhost:9090 #Address of MinIO service
  bucketName: mall-minio #Bucket name
  accessKey: minioadmin #Access key
  secretKey: minioadmin #Access key
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000 #Service request connection timeout（Millisecond）
  ReadTimeout: 3000 #Service request processing timeout time (Millisecond)