server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tehran
    username: root
    password: root
    druid:
      initial-size: 5 #Initial connection pool size
      min-idle: 10 #Minimum number of idle connections
      max-active: 20 #Maximum number of connections
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #Do not count these request data
      stat-view-servlet: #Login username and password to access the monitoring webpage
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
  redis:
    host: localhost # Redis server address
    database: 0 # Redis database index (default is 0)
    port: 6379 # Redis server connection port
    password:  # Redis server connection password (empty by default)
    timeout: 3000ms # Connection timeout (ms)
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
  application:
    name: mall-portal
# Customize Spring Boot Info actuator
info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}
  application.encoding: @project.build.sourceEncoding@
  application.name: ${spring.application.name}
  spring.boot.version: @spring-boot.version@

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management: #Open SpringBoot Admin monitoring
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Custom redis key
redis:
  database: mall
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # Verification code expiration time
    common: 86400 # 24 hours

# Message queue definition
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000 #Service request connection timeout time (ms)
  ReadTimeout: 3000 #Service request processing timeout time (ms)
